version: "3.8"

services:
  rl_research:
    build:
      context: .
      dockerfile: Dockerfile
    image: rl-research:latest
    command: /bin/bash -c "python -u main.py"
    volumes:
      - .:/home/rl_research
