services:
  rl-genesis:
    build: 
      context: .
      dockerfile: Dockerfile
    image: rl-genesis:latest
    environment:
      - CUDA_VISIBLE_DEVICES=0
      - NVIDIA_VISIBLE_DEVICES=0    
    # command: tail -f /dev/null
    command: python3 main.py
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
