services:
  rl-genesis:
    build: 
      context: .
      dockerfile: Dockerfile
    image: rl-genesis:latest
    environment:
      - CUDA_VISIBLE_DEVICES=0
      - NVIDIA_VISIBLE_DEVICES=0    
    volumes:
      - ./logs/:/src/logs/
    command: tail -f /dev/null
    # command: python3 train.py
    ports:
      - "35629:6006"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
